=== Kemp-J/dfc-data/Schemas/fleet/famous_admiral.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://dfc/schemas/fleet/famous_admiral.json",
    "title": "DFC Famous Admiral Data",
    "description": "Data file for a Famous Admiral.",
    "type": "object",
    "required": [
        "admiral",
        "admiral_level",
        "class",
        "type",
        "admiral_points",
        "ship_points",
        "points",
        "tonnage",
        "base_size",
        "profile",
        "weapons",
        "load",
        "fleet_admiral_abilities",
        "admiral_abilities",
        "flavour"
    ],
    "additionalProperties": false,
    "properties": {
        "admiral":                 { "type": "string" },
        "admiral_level":           { "type": "integer" },
        "class":                   { "type": "string" },
        "type":                    { "type": "string" },
        "admiral_points":          { "type": "integer" },
        "ship_points":             { "type": "integer" },
        "points":                  { "type": "integer" },
        "tonnage":                 { "$ref": "https://dfc/schemas/defs.json#/$defs/Tonnage" },
        "base_size":               { "type": "integer" },
        "profile":                 { "$ref": "https://dfc/schemas/defs.json#/$defs/ShipProfile" },
        "weapons":                 { "type": "array", "items": { "$ref": "https://dfc/schemas/defs.json#/$defs/Weapon" } },
        "load":                    { "type": "array", "items": { "$ref": "https://dfc/schemas/defs.json#/$defs/LoadEntry" } },
        "upgrades":                { "type": "array", "items": { "$ref": "https://dfc/schemas/defs.json#/$defs/UpgradeEntry" } },
        "rules":                   { "type": "array", "items": { "$ref": "https://dfc/schemas/defs.json#/$defs/Rule" } },
        "fleet_admiral_abilities": { "description": "Number of fleet abilities this admiral may take.", "type": "integer" },
        "admiral_abilities":       { "type": "array", "items": { "$ref": "https://dfc/schemas/defs.json#/$defs/Ability" } },
        "usable_in":               { "type": "array", "items": { "$ref": "https://dfc/schemas/defs.json#/$defs/UsableInEntry" } },
        "flavour":                 { "type": "string" }
    }
}

=== Kemp-J/dfc-data/Data/Bioficer/atom.json
{
    "admiral": "Atom",
    "admiral_level": 2,
    "class": "Scion",
    "type": "Battlecruiser",
    "admiral_points": 45,
    "ship_points": 150,
    "points": 195,
    "tonnage": "H",
    "base_size": 50,
    "profile": {
        "Thrust": 8,
        "Scan": 10,
        "Sig": 4,
        "Hull": 12,
        "ES": "4+",
        "KS": "4+",
        "BS": "5+",
        "G": "1",
        "Special": [
            "Vanguard-6\""
        ]
    },
    "weapons": [
        {
            "Name": "Godray Lightvice",
            "Profiles": [
                {
                    "Name": "Anti-Ship",
                    "Arc": "F/S",
                    "Att": 5,
                    "Lock": "2+",
                    "DMG": 3,
                    "Type": "K",
                    "Special": [
                        "Alt-1",
                        "Bloom-1",
                        "Close Action",
                        "Focused",
                        "Scald-1"
                    ]
                },
                {
                    "Name": "Bombardment",
                    "Arc": "F/S",
                    "Att": 5,
                    "Lock": "4+",
                    "DMG": 3,
                    "Type": "K",
                    "Special": [
                        "Alt-1",
                        "Bloom-1",
                        "Bombardment",
                        "Close Action",
                        "Focused",
                        "Scald-1"
                    ]
                }
            ],
            "Rule": "This weapon's Bombardment profile may target Dropsites within scan range as if it did not have the Close Action special rule.\nIf either of this weapon's profiles target a Dropsite containing a friendly Bioficer Deployable Feature, friendly Battalions assigned to that Feature ignore Collateral Damage due to this weapon."
        }
    ],
    "load": [],
    "fleet_admiral_abilities": 1,
    "admiral_abilities": [
        {
            "Cost": "1AP",
            "Name": "Vice Lightly",
            "Effect": "When you assign targets to a weapon with \"Lightvice\" in its name, that weapon ignores its Focused rule for that attack."
        }
    ],
    "flavour": ""
}

=== Kemp-J/dfc-data/Data/Bioficer/ascendant.json
{
    "admiral": "Ascendant",
    "admiral_level": 4,
    "class": "Zenith",
    "type": "Dreadnought",
    "admiral_points": 85,
    "ship_points": 520,
    "points": 605,
    "tonnage": "C",
    "base_size": 60,
    "profile": {
        "Thrust": 6,
        "Scan": 14,
        "Sig": 10,
        "Hull": 22,
        "ES": "3+",
        "KS": "3+",
        "BS": "5+",
        "G": "1",
        "Special": [
            "Marines-3",
            "Reinforced Armour"
        ]
    },
    "weapons": [
        {
            "Name": "Giga Lightvice",
            "Arc": "F",
            "Att": 8,
            "Lock": "2+",
            "DMG": 3,
            "Type": "K",
            "Special": [
                "Bloom-1",
                "Close Action",
                "Focused",
                "Scald-2"
            ],
            "Rule": "When determining potential targets for this weapon, you may use an unmodifiable Scan of 7\" instead of this Ship's Scan value."
        },
        {
            "Name": "Grand Bisector",
            "Arc": "FN",
            "Att": 5,
            "Lock": "3+",
            "DMG": 3,
            "Type": "E",
            "Special": [
                "Bloom-2",
                "Calibre-H/C",
                "Crippling",
                "Focused",
                "Penetrator"
            ]
        },
        {
            "Name": "Scythes",
            "Arc": "FN",
            "Att": 8,
            "Lock": "4+",
            "DMG": 1,
            "Type": "E",
            "Special": [
                "Anti Wing",
                "Fusillade-3",
                "Reave-1"
            ]
        },
        {
            "Name": "Scythes",
            "Arc": "FN",
            "Att": 8,
            "Lock": "4+",
            "DMG": 1,
            "Type": "E",
            "Special": [
                "Anti Wing",
                "Fusillade-3",
                "Reave-1"
            ]
        }
    ],
    "load": [
        {
            "Load": "Fighters & Bombers",
            "Launch": 5,
            "Special": []
        },
        {
            "Load": "Boarding Pods",
            "Launch": 3,
            "Special": []
        }
    ],
    "rules": [
        {
            "Name": "High Velocity Boarding Pods",
            "Text": "This Ship's Boarding Pods may be used against targets up to 6\" away."
        }
    ],
    "fleet_admiral_abilities": 2,
    "admiral_abilities": [
        {
            "Cost": "2AP",
            "Name": "Overwatch",
            "Effect": "When you activate this Ship on General Quarters, you may choose to forgo attacking with this Ship. If you do, this Ship goes on Overwatch until the end of the round or until it declares the use of Overwatch. At the end of any enemy Group's activation, if that Group moved through this Ship's Front arc and was in weapons range while doing so, you may declare the use of Overwatch against that Group. When you use Overwatch, this Ship immediately makes an Attack as if on General Quarters against the enemy Group, even if it is out of arc and weapon range."
        }
    ],
    "flavour": ""
}

=== Kemp-J/dfc-data/Data/Resistance/magellan.json
{
    "admiral": "Magellan",
    "admiral_level": 3,
    "class": "Coloniser",
    "type": "Interstellar Dreadnought",
    "admiral_points": 45,
    "ship_points": 525,
    "points": 570,
    "tonnage": "C",
    "base_size": 60,
    "profile": {
        "Thrust": 8,
        "Scan": 10,
        "Sig": 16,
        "Hull": 26,
        "ES": "4+",
        "KS": "4+",
        "BS": "4+",
        "G": "1",
        "Special": [
            "Command Ship-2"
        ]
    },
    "weapons": [
        {
            "Name": "10K Mass Driver Turret",
            "Arc": "F/S",
            "Att": 2,
            "Lock": "3+",
            "DMG": 2,
            "Type": "K",
            "Special": [
                "Calibre-H/C",
                "Critical-2",
                "Penetrator",
                "Volley-2"
            ]
        },
        {
            "Name": "10K Mass Driver Turret",
            "Arc": "F/S",
            "Att": 2,
            "Lock": "3+",
            "DMG": 2,
            "Type": "K",
            "Special": [
                "Calibre-H/C",
                "Critical-2",
                "Penetrator",
                "Volley-2"
            ]
        },
        {
            "Name": "Heavy Dual Vent Cannon Turret",
            "Arc": "F/S",
            "Att": 4,
            "Lock": "3+",
            "DMG": 2,
            "Type": "E",
            "Special": [
                "Fusillade-2",
                "Overcharge",
                "Reave-1"
            ]
        },
        {
            "Name": "Heavy Dual Vent Cannon Turret",
            "Arc": "F/S",
            "Att": 4,
            "Lock": "3+",
            "DMG": 2,
            "Type": "E",
            "Special": [
                "Fusillade-2",
                "Overcharge",
                "Reave-1"
            ]
        },
        {
            "Name": "NC-16 Missiles",
            "Arc": "F/S/R",
            "Att": 4,
            "Lock": "3+",
            "DMG": 1,
            "Type": "K",
            "Special": [
                "Close Action"
            ]
        }
    ],
    "load": [
        {
            "Load": "Fighters & Bombers",
            "Launch": 4,
            "Special": []
        },
        {
            "Load": "Bulk Landers & Fire Ships",
            "Launch": 4,
            "Special": []
        }
    ],
    "rules": [
        {
            "Name": "Assault Carrier",
            "Text": "This ship must take two 10k Mass Drivers, two Heavy Vent Cannons, a Drive Refit (that's been heavily jury-rigged and does not take up a hardpoint or points), and the following Launch Assets:"
        }
    ],
    "fleet_admiral_abilities": 1,
    "admiral_abilities": [
        {
            "Cost": "2AP",
            "Name": "Magellan Expedition",
            "Effect": "When you launch Bulk Landers from this Ship or a Ship within 6\" of it, you may have that Ship launch an additional 2 or 4 Bulk Landers. Any Ship that does takes that much damage (causing Crippling Effects and Explosions where applicable)."
        }
    ],
    "flavour": ""
}

=== Kemp-J/dfc-data/Data/PHR/claudia_rhee.json
{
    "admiral": "Claudia Rhee",
    "admiral_level": 4,
    "class": "Heracles",
    "type": "Battleship",
    "admiral_points": 75,
    "ship_points": 235,
    "points": 310,
    "tonnage": "H",
    "base_size": 50,
    "profile": {
        "Thrust": 6,
        "Scan": 10,
        "Sig": 10,
        "Hull": 22,
        "ES": "3+",
        "KS": "3+",
        "BS": "5+",
        "G": "1",
        "Special": []
    },
    "weapons": [
        {
            "Name": "Heavy Calibre Triple Broadside",
            "Arc": "B",
            "Att": 3,
            "Lock": "3+",
            "DMG": 3,
            "Type": "K",
            "Special": [
                "Calibre-H/C",
                "Penetrator",
                "Volley-2"
            ]
        },
        {
            "Name": "Dark Matter Cannon",
            "Arc": "FN",
            "Att": 4,
            "Lock": "2+",
            "DMG": 2,
            "Type": "E",
            "Special": [
                "Crippling",
                "Critical-1",
                "Penetrator"
            ]
        },
        {
            "Name": "Hornet Drones",
            "Arc": "F/S/R",
            "Att": 5,
            "Lock": "3+",
            "DMG": 1,
            "Type": "K",
            "Special": [
                "Close Action"
            ]
        }
    ],
    "load": [],
    "rules": [],
    "fleet_admiral_abilities": 2,
    "admiral_abilities": [
        {
            "Cost": "2AP",
            "Name": "High-G Manouevre",
            "Effect": "When a friendly Group is given a Max Thrust order, it may turn as if it was on General Quarters."
        }
    ],
    "upgrades": [],
    "flavour": "Claudia Rhee is a rarity amongst the PHR. Once a Siren, her tactical aptitude and control over countless Familiars gained her a place as a Medusa, one of the most elite members of the already elite Siren Corps. She earned her place in the captains chair when her ship was ambushed by Shaltari pirates. Their initial volley had struck right through the ship's CIC, killing many of the command crew and leaving vital systems unmanned. Acting immediately, Claudia networked her Familiars with the ships' systems, restored order and brought weapons to bear. Her quick thinking saved the lives of many that day and while the ship itself was unsalvageable, Claudia was approached with an offer that would one day see her commanding not only her own ship, but an entire fleet.\nAs the daughter of Octavia Rhee, there has been high expectations of her since the day she was born. Fortunately for her she has exceeded every single one of them. She was able to control multiple Familiars by the time her peers were only just able to operate a single Familiar. She aced every single combat proficiency test thrown at her and her field operation record is impeccable.\nThough despite all of this she still lives in her mother's shadow, made even darker by her recent sacrifice in the Shangri-La system. While Claudia is determined to make those responsible pay, the alliances made before the Battle of Earth make this a difficult prospect as of late. It is only a matter of time, however, before that all breaks down, countless simulations calculated by her Familiars have shown her that over and over again."
}

=== Kemp-J/dfc-data/Data/Resistance/typhoon_vasquez.json
{
    "admiral": "Typhoon Vasquez",
    "admiral_level": 2,
    "class": "Heavy Cruiser",
    "type": "Heavy Cruiser",
    "admiral_points": 45,
    "ship_points": 113,
    "points": 158,
    "tonnage": "M",
    "base_size": 40,
    "profile": {
        "Thrust": 5,
        "Scan": 10,
        "Sig": 6,
        "Hull": 13,
        "ES": "3+",
        "KS": "4+",
        "BS": "6+",
        "G": "1",
        "Special": [
            "Reinforced Armour"
        ]
    },
    "weapons": [
        {
            "Name": "N-11 Artillery Cannon Turret",
            "Arc": "F/S",
            "Att": 3,
            "Lock": "4+",
            "DMG": 1,
            "Type": "K",
            "Special": [
                "Fusillade-1",
                "Low Power",
                "Linked-1"
            ]
        },
        {
            "Name": "N-11 Artillery Cannon Turret",
            "Arc": "F/S",
            "Att": 3,
            "Lock": "4+",
            "DMG": 1,
            "Type": "K",
            "Special": [
                "Fusillade-1",
                "Low Power",
                "Linked-1"
            ]
        },
        {
            "Name": "N-8 Artillery Cannon Bank",
            "Arc": "B",
            "Att": 6,
            "Lock": "5+",
            "DMG": 1,
            "Type": "K",
            "Special": [
                "Fusillade-2",
                "Low Power",
                "Volley-2"
            ]
        },
        {
            "Name": "N-8 Artillery Cannon Bank",
            "Arc": "B",
            "Att": 6,
            "Lock": "5+",
            "DMG": 1,
            "Type": "K",
            "Special": [
                "Fusillade-2",
                "Low Power",
                "Volley-2"
            ]
        }
    ],
    "load": [],
    "rules": [
        {
            "Name": "Bullet Baron",
            "Text": "This ship must take two N-8 Artillery Cannon Banks, two N-11 Artillery Cannon Turrets, Ablative Armour, and a Scanner Array (that's been heavily jury rigged and does not take up a hardpoint or points)."
        }
    ],
    "fleet_admiral_abilities": 1,
    "admiral_abilities": [
        {
            "Cost": "2AP*",
            "Name": "Artillery Strike",
            "Effect": "When you assign targets to a Weapon System with \"Artillery\" in its name, that Weapon System's damage type becomes Core for those attacks. If that Weapon System is on a H or C tonnage Ship this Ability costs 3AP."
        }
    ],
    "upgrades": [],
    "flavour": "Typhoon Vasquez is the Head Engineer of the Red Baron, a pre-war ship used as a test-bed for various ammunition types designed for then-current Artillery Cannons. Vasquez's Battlegroup contains a large number of industrial ships, including the Andar Errente, a pre-war Industrial Raft. Thanks to copious amounts of manufacturing ability, Vasquez is able to be very liberal with the application of the various bootleg munitions produced by his fleet.\nVasquez's combat capable ships were present at the Battle for Earth and managed to score several Scourge kills. The Red Baron spent most of the engagement firing on any and every cylinder it could find. Vasquez's battle tactics seemed to either be genius, drawing most of the Scourge return fire towards the Red Baron and its ablative armour, or the absolute lunacy of being on constant weapons-free."
}

=== Kemp-J/dfc-data/Data/PHR/helena_of_asgard.json
{
    "admiral": "Helena of Asgard",
    "admiral_level": 2,
    "class": "Pompeius",
    "type": "Battlecruiser",
    "admiral_points": 60,
    "ship_points": 140,
    "points": 200,
    "tonnage": "H",
    "base_size": 50,
    "profile": {
        "Thrust": 10,
        "Scan": 8,
        "Sig": 6,
        "Hull": 15,
        "ES": "3+",
        "KS": "4+",
        "BS": "6+",
        "G": "1",
        "Special": [
            "Vanguard-4\""
        ]
    },
    "weapons": [
        {
            "Name": "Heavy Quad Battery",
            "Profiles": [
                {
                    "Name": "Anti-Capital",
                    "Arc": "F",
                    "Att": 4,
                    "Lock": "3+",
                    "DMG": 2,
                    "Type": "K",
                    "Special": [
                        "Alt-1",
                        "Calibre-H/C",
                        "Critical-1",
                        "Penetrator"
                    ]
                },
                {
                    "Name": "Flak",
                    "Arc": "F",
                    "Att": 12,
                    "Lock": "2+",
                    "DMG": 1,
                    "Type": "K",
                    "Special": [
                        "Alt-1",
                        "Fusillade-4"
                    ]
                }
            ]
        }
    ],
    "load": [],
    "rules": [
        {
            "Name": "Cull the Weak",
            "Text": "Heavy Quad Battery (Flak) may only be used to attack Ships of L Tonnage."
        }
    ],
    "fleet_admiral_abilities": 1,
    "admiral_abilities": [
        {
            "Cost": "2AP",
            "Name": "Experimental Munitions",
            "Effect": "When you assign targets to weapons, select one of those weapons with the Calibre-X special rule. That weapon gains the benefits of its Calibre-X special rule regardless of the Tonnage of the target Group for that attack."
        }
    ],
    "flavour": "Helena of Asgard is one of the most aggressive ranking officers active in the Asgard System. Part of the force tasked with destroying as many UCM Strike Carriers as possible. Retreating groups learned to steer clear of her flagship's Heavy Quad Battery lest the entire group be obliterated.\nWhile the UCM believe Helena is part of the external PHR forces, the truth is that Helena is an Asgard native. During the PHR's initial dealings with the resistance forces on Asgard Prime a young Helena started a rapport with PHR naval personnel, listening to tales of sights she would never see staying put on her home planet. Resolved to go with the returning PHR forces she sneaked aboard an outbound PHR transport. To her new allies, however, her infiltration attempt was painfully obvious.\nAlthough among plenty of other Asgardians that had decided to join their PHR allies, Helena showed great enthusiasm and promise in fleet-based operations. Proving herself again and again, Helena returned to Asgard Prime shortly before the ambush on the UCM fleet."
}

=== Kemp-J/dfc-data/Data/Bioficer/atlas.json
{
    "admiral": "Atlas",
    "admiral_level": 2,
    "class": "Catastrophe",
    "type": "Heavy Cruiser",
    "admiral_points": 45,
    "ship_points": 110,
    "points": 155,
    "tonnage": "M",
    "base_size": 40,
    "profile": {
        "Thrust": 7,
        "Scan": 8,
        "Sig": 4,
        "Hull": 9,
        "ES": "4+",
        "KS": "4+",
        "BS": "5+",
        "G": "1",
        "Special": [
            "Porter S-1"
        ]
    },
    "weapons": [
        {
            "Name": "Heavy Lightvice",
            "Arc": "F",
            "Att": 5,
            "Lock": "2+",
            "DMG": 2,
            "Type": "K",
            "Special": [
                "Close Action",
                "Focused"
            ]
        },
        {
            "Name": "Thermator",
            "Arc": "F",
            "Att": 3,
            "Lock": "4+",
            "DMG": 2,
            "Type": "E",
            "Special": [
                "Overcharge",
                "Scald-1"
            ]
        }
    ],
    "load": [],
    "rules": [
        {
            "Name": "One Upsmanship",
            "Text": "If this Admiral is your highest level Admiral, whenever your opponent uses an Ability, roll a dice. On a 4+, you gain 1AP."
        }
    ],
    "fleet_admiral_abilities": 1,
    "admiral_abilities": [
        {
            "Cost": "2AP",
            "Name": "Emergency Reattachment Protocol",
            "Effect": "When an enemy would destroy one of your Payload Ships, it is not destroyed and is instead reattached to a valid Porter Ship within 6\"."
        }
    ],
    "upgrades": [],
    "flavour": ""
}
