=== Kemp-J/dfc-data/Schemas/fleet/hero.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://dfc/schemas/fleet/hero.json",
    "title": "DFC Hero Ship Data",
    "description": "Data file for a Hero ship.",
    "type": "object",
    "required": [
        "hero",
        "ship",
        "type",
        "points",
        "tonnage",
        "base_size",
        "profile",
        "weapons",
        "load",
        "known_ships",
        "flavour"
    ],
    "additionalProperties": false,
    "properties": {
        "hero":              { "type": "string" },
        "ship":              { "type": "string" },
        "type":              { "type": "string" },
        "points":            { "type": "integer" },
        "tonnage":           { "$ref": "https://dfc/schemas/fleet/defs.json#/$defs/Tonnage" },
        "base_size":         { "type": "integer" },
        "profile":           { "$ref": "https://dfc/schemas/fleet/defs.json#/$defs/ShipProfile" },
        "weapons":           { "type": "array", "items": { "$ref": "https://dfc/schemas/fleet/defs.json#/$defs/Weapon" } },
        "load":              { "type": "array", "items": { "$ref": "https://dfc/schemas/fleet/defs.json#/$defs/LoadEntry" } },
        "upgrades":          { "type": "array", "items": { "$ref": "https://dfc/schemas/fleet/defs.json#/$defs/UpgradeEntry" } },
        "rules":             { "type": "array", "items": { "$ref": "https://dfc/schemas/fleet/defs.json#/$defs/Rule" } },
        "admiral_abilities": { "type": "array", "items": { "$ref": "https://dfc/schemas/fleet/defs.json#/$defs/Ability" } },
        "usable_in":         { "type": "array", "items": { "$ref": "https://dfc/schemas/fleet/defs.json#/$defs/UsableInEntry" } },
        "known_ships":       { "type": "array", "items": { "type": "string" } },
        "flavour":           { "type": "string" }
    }
}

=== Kemp-J/dfc-data/Data/PHR/avram_bei.json
{
    "hero": "Avram Bei",
    "ship": "Subatomic",
    "type": "Heavy Destroyer",
    "points": 96,
    "tonnage": "L",
    "base_size": 30,
    "profile": {
        "Thrust": 12,
        "Scan": 8,
        "Sig": 2,
        "Hull": 8,
        "ES": "4+",
        "KS": "5+",
        "BS": "6+",
        "G": "1",
        "Special": [
            "Hero",
            "Unique"
        ]
    },
    "weapons": [
        {
            "Name": "Neutron Missile Silo",
            "Arc": "F/S",
            "Att": 3,
            "Lock": "2+",
            "DMG": 2,
            "Type": "E",
            "Special": [
                "Close Action",
                "Crippling",
                "Penetrator"
            ]
        },
        {
            "Name": "Twin Supernova Laser",
            "Arc": "FN",
            "Att": 3,
            "Lock": "3+",
            "DMG": 2,
            "Type": "E",
            "Special": [
                "Burnthrough-2",
                "Flash-2",
                "Focused"
            ]
        }
    ],
    "load": [],
    "known_ships": [
        "Subatomic"
    ],
    "flavour": "Neutron missiles are a rightly feared branch of PHR weapons technology, but until now they have been confined to the largest capital ships due to warhead core containment requirements prior to launch. A single new ship, Subatomic, has a full battery of these top-tier munitions though, complimented with twinned lasers, despite its slightly enlarged destroyer tonnage. It's understood that this ship has yet to receive clearance for wider construction. Possible crew losses due to containment failures have been rumoured although secrecy surrounds the vessel.\nIts famous captain, Avram Bei, is part of a splinter fleet that has yet to declare for one side or the other in the PHR's recent schism, preferring to focus on their bloody pursuit of Shaltari pirates near Aaru before considering theological matters, or whether theology is even the right way of thinking about the White Sphere. Bei is a practical, non-nonsense warrior with little interest in the big picture. He is known to relish fighting at the heart of any engagement, a joy undimmed even though half of his frequently injured body has been replaced with combat augmetics."
}

=== Kemp-J/dfc-data/Data/UCM/rhiannon_major.json
{
    "hero": "Rhiannon Major",
    "ship": "Leaden Triad",
    "type": "Heavy Destroyer",
    "points": 71,
    "tonnage": "L",
    "base_size": 30,
    "profile": {
        "Thrust": 8,
        "Scan": 6,
        "Sig": 4,
        "Hull": 6,
        "ES": "3+",
        "KS": "4+",
        "BS": "6+",
        "G": "1",
        "Special": [
            "Hero",
            "Unique"
        ]
    },
    "weapons": [
        {
            "Name": "Artillery Cannon",
            "Arc": "F",
            "Att": 1,
            "Lock": "4+",
            "DMG": 2,
            "Type": "K",
            "Special": [
                "Calibre-H/C",
                "Fusillade-1",
                "Low Power"
            ]
        },
        {
            "Name": "Artillery Cannon",
            "Arc": "F",
            "Att": 1,
            "Lock": "4+",
            "DMG": 2,
            "Type": "K",
            "Special": [
                "Calibre-H/C",
                "Fusillade-1",
                "Low Power"
            ]
        },
        {
            "Name": "Artillery Cannon",
            "Arc": "F",
            "Att": 1,
            "Lock": "4+",
            "DMG": 2,
            "Type": "K",
            "Special": [
                "Calibre-H/C",
                "Fusillade-1",
                "Low Power"
            ]
        }
    ],
    "load": [],
    "known_ships": [
        "- Leaden Triad"
    ],
    "flavour": "Leaden Triad is a new, experimental vessel designed and built by the restored Eden Drive Yards Corporation. This pre-war colossus was ended by the Scourge invasion, but this reincarnation is based in its recaptured shipyards, and the new corporation has all the recovered tech of its predecessor, including its work on the largest chemical guns ever built. Though they never got a chance to enter service, three prototypes were recovered and have been installed aboard a unique heavy destroyer hull.\nCaptain Rhiannon Major, already the UCM's finest naval gunnery officer at just 34 years of age, has been given command. Though not a natural leader, her icy bravery and uncanny intelligence are the natural fit to shepherd this project into combat testing. Already, she has demonstrated the devastating power of this antique technology when writ large by deftly annihilating two Bioficer battlecruisers. These guns hurl house-sized shells at vast muzzle energy with negligible power drain, allowing full manoeuvrability and systems use while firing weapons far exceeding this ship's tonnage grade. However, despite Major's calculations and brilliant heat management, frequent and ultra-costly barrel changes seem inevitable."
}
